[package]
name = "lambda_test"
version = "0.1.0"
authors = ["Emmanuel Thioux"]
edition = "2018"

[dependencies]
lambda_bootstrap = { path = "../lambda_bootstrap" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.79"
json = "0.12.4"